version: '3'
services:
  # Node.js Server
  notes-${NODE_ENV}-api:
    build: ./api
    container_name: notes-${NODE_ENV}-api
    env_file:
      - ./config/${NODE_ENV}.env
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - notes-${NODE_ENV}-db
    command: npm run ${NODE_ENV}
    
  # PostgreSQL Database
  notes-${NODE_ENV}-db:
    image: postgres:15
    container_name: notes-${NODE_ENV}-db
    env_file:
      - ./config/${NODE_ENV}.env
    volumes:
      - notes-${NODE_ENV}-data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:${PGPORT}"
volumes:
  notes-${NODE_ENV}-data:
