version: '3'
services:
  # Node.js Server
  notes-${NODE_ENV}-api:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV}
    container_name: ${APP}-${NODE_ENV}-api
    env_file:
      - ./src/private/${NODE_ENV}.env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - ${APP}_${NODE_ENV}_network

    depends_on:
      - ${APP}-${NODE_ENV}-db
    command: npm run ${NODE_ENV}

# PostgreSQL Database
  ${APP}-${NODE_ENV}-db:
    image: postgres:15
    container_name: ${APP}-${NODE_ENV}-db
    env_file:
      - ./src/private/${NODE_ENV}.env
    volumes:
      - ${APP}-${NODE_ENV}-data:/var/lib/postgresql/data
    ports:
      - "${PGPORT}:${PGPORT}"
    networks:
      - ${APP}_${NODE_ENV}_network
volumes:
  ${APP}-${NODE_ENV}-data:
  
networks:
  ${APP}_${NODE_ENV}_network:
    driver: bridge
