FROM --platform=${TARGETPLATFORM} gcloudbox

WORKDIR /repo

USER node

CMD firebase emulators:start --project ${REACT_APP_FIREBASE_PROJECT_ID} --config firebase.json.${REACT_APP_NODE_ENV} --import /var/lib/firebase/data --export-on-exit /var/lib/firebase/data
