# fly.toml app configuration file generated for divine-resonance-8856 on 2023-09-11T12:42:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-resonance-8856"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
