#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")"

if ! docker login --username AWS --password-stdin 111168381990.dkr.ecr.us-east-1.amazonaws.com < private/docker-login
then
  echo docker login failed.
  exit 1
fi
if ! docker build --platform linux/amd64 -t devops-fall2023 -f Dockerfile.amazonlinux-node .
then
  echo docker build failed.
  exit 1
fi

if ! docker tag devops-fall2023:latest 111168381990.dkr.ecr.us-east-1.amazonaws.com/devops-fall2023:latest
then
  echo docker tag failed.
  exit 1
fi

if ! docker push 111168381990.dkr.ecr.us-east-1.amazonaws.com/devops-fall2023:latest
then
   docker push failed.
   exit 1
fi
