FROM node:18

RUN apt update \
  && DEBIAN_FRONTEND=noninteractive apt install -y \
  build-essential cmake curl git git-crypt gnupg openssl openssh-server python3 sudo \
  && apt clean \
  && /bin/rm -rf /var/lib/apt/lists/*

USER node

VOLUME /repo
WORKDIR /repo

CMD bash -i

