#!/bin/bash

built() {
    docker image ls --format '{{.ID}}:{{.Repository}}' | grep ":$1" | cut -d: -f1
}

built_timestamp() {
    id="$1"
    iso=$(docker inspect --format '{{.Created}}' "$id")
    trunc=$(echo $iso | cut -d. -f1)
    date -j -f "%Y-%m-%dT%H:%M:%S" "$trunc" "+%s"
}

modification_timestamp() {
    stat -f "%m" "$1"
}

extension="$(basename "${BASH_SOURCE[0]}")"
tag=$(basename "${BASH_SOURCE[0]}" | tr '[:upper:]' '[:lower:]')
tag="${tag// /_}"

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
dockerfile="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)/Dockerfile.$extension"

if ! docker build -t "$tag" -f "$dockerfile" "$dir"
then
    echo "Build failed."
    exit 1
fi

CONTAINER_USER=cloudsdk
docker run -u $CONTAINER_USER -v "$HOME/.gitconfig:/home/$CONTAINER_USER/.gitconfig:rw" -v "$HOME/.ssh:/home/$CONTAINER_USER/.ssh:rw" -v "$HOME/.gnupg:/home/$CONTAINER_USER/.gnupg:rw" -v "$(pwd):/repo" --rm -it "$tag" bash -i
