#!/usr/bin/awk -f

{
    start = 1
    while (match(substr($0, start), /[0-9a-fA-F]{17,}/)) {
        hex_pattern = substr($0, RSTART + start - 1, RLENGTH)
	random_key_length = int(RLENGTH / 2)
        cmd = "openssl rand -hex " random_key_length
        cmd | getline random_key
        close(cmd)
        sub(hex_pattern, random_key)
        start = RSTART + RLENGTH + start
    }
    print
}
